### ISSUE TITLE
Add status badges to the README

### ISSUE THREAD

**Issue by jlgimeno** [kjaymiller/render_engine#205]
As this gets closer to an eventual 1.0 release, adding status badges would allow users and contributors to see at a glance what the current state of the project.

**Comment by kjaymiller** [comment]
PyTest Testing Badge added with d359fc5ba1b2ba2789a806bd9eca2d5d3adf027d.

@jlgimeno - Not sure what other badges would be good to add

**Comment by jlgimeno** [comment]
This is good for now.  As time goes on and we add other CI tasks, we can add to these (e.g. coverage, build status, etc).

**Comment by kjaymiller** [comment]
@all-contributors please add @jlgimeno for doc

**Comment by kjaymiller** [comment]
@all-contributors please add @jlgimeno for doc
