### ISSUE TITLE
Plugin support?

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/render_engine#42]
Are there plans to support plugins / extensions / etc. in Render Engine? In the spirit of being "Flask Like", plugins could be a nice way to ship third- (or first-) party features that are not part of the core site generator framework. For example,

- Template rendering: #39 proposes adding support for mustache templates. A plugin system that allows registration of plugins to handle different file types would provide a convenient entrypoint for different template languages and other tools like css framework compilers. See also: Jekyll's documentation on [Converters](https://jekyllrb.com/docs/plugins/converters/), which includes a hook for specifying matching file types (`matches`).
- Feed generation: #21 proposes adding JSON feed support. [`jekyll-feed`](https://github.com/jekyll/jekyll-feed) is a popular plugin used to generate Atom feeds for Jekyll sites.

Both of these could be accomplished within a given site by overriding the `render` method today, but this approach does not allow for easily shareable and reusable components as well as a plugin system would. I don't want to suggest technical implementation details before this feature is discussed, but I think that a minimum starting point would require at least 1) a way to register plugins for a site and 2) events / hooks that plugins can register callbacks against.

**Comment by kjaymiller** [comment]
The long term answer is yes, but after the core functionality was fully tested, and the entry points for plugins were identified.

I’ve been thinking about these for a while and this was also something that others have asked for.

Blog itself (and microblog) should be plugins. Event if they are standard inclusions. The main question is should a plugins be a swappable object to append or replace an existing `Page` `Collection` or `Site` Or should it be individual entry and exit points that allow for appending to the existing three objects only?

**Comment by kjaymiller** [comment]
Update a lot of work on this has begun and is available in `render-engine==2023.1.3a4`+. It will be better solidified in the 2023.1.3 release.
