### ISSUE TITLE
Correct way to build the docs?

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/render_engine#44]
`make html` expects `sphinx-build` to be available on the path, but when setting up a development environment using `poetry install`, this executable is not on the path. Modifying `Makefile` to change `sphinx-build` to `poetry run sphinx-build` allows the builds to run successfully, but I don't know if this is the desired setup. Should the `Makefile` be modified in this way, or should I be setting up my docs environment differently?

**Comment by kjaymiller** [comment]
with moving to mkdocs and no-longer using poetry - this should have been fixed. The docs still need plenty of love but they are at least building.
