### ISSUE TITLE
Docs on Read the Docs are incomplete

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/render_engine#45]
The docs hosted at https://render-engine.readthedocs.io/en/latest/ are missing all of the autodoc documentation, but if I render the docs locally (after modifying my local `Makefile` as described in #44) all docs are present. After a bit of searching through the documentation build logs, it seems like the project may not be installed by RTD before building? I set up a different sphinx environment without installing `render_engine`, and resulting documentation build seemed to be the same as what I see on RTD. One possible explanation: if the RTD "Install Project" setting (under the "Advanced Settings" Admin section) is not enabled, that step might be getting skipped and ignoring the missing components to build mostly blank docs.

**Comment by kjaymiller** [comment]
@all-contributors please add @jonafato for code
