### ISSUE TITLE
Rendered content remains in output directory even after source content is removed

### ISSUE THREAD

**Issue by jonafato** [kjaymiller/render_engine#46]
If you move or remove content from a site, the previously rendered version of that content is not removed, and instead outdated render artifacts are left behind. I expected the output directory to contain only the content relevant to the last render. Given the example below:

```python
from render_engine import Site, Collection, Page

class Site(Site):
    site_vars = {
        "SITE_TITLE": "Example Site",
        "SITE_URL": "https://example.com",
        "some_template_variable": "Pass this to every page",
    }

site = Site(static="static")

@site.render_page
class About(Page):
    template = "base.html"
    title = "About"
    slug = "about"
    markdown = "hello, world"
```
```sh
» python site.py
╭──────────────────────────╮
│ Rendering Site           │
╰──────────────────────────╯

 Site Config Keys Imported: ['SITE_TITLE', 'SITE_URL', 'some_template_variable']

» ls output/
about.html  static/
```

This renders as expected, but if I then change the `slug` on my `About` page and re-render the site without removing the contents of the output directory, I end up with both copies:

```python
from render_engine import Site, Collection, Page

class Site(Site):
    site_vars = {
        "SITE_TITLE": "Example Site",
        "SITE_URL": "https://example.com",
        "some_template_variable": "Pass this to every page",
    }

site = Site(static="static")

@site.render_page
class About(Page):
    template = "base.html"
    title = "About"
    slug = "index"
    markdown = "hello, world"
```
```sh
» python site.py
╭──────────────────────────╮
│ Rendering Site           │
╰──────────────────────────╯

 Site Config Keys Imported: ['SITE_TITLE', 'SITE_URL', 'some_template_variable']

» ls output/
about.html  index.html  static/
```

**Comment by kjaymiller** [comment]
There used to be a `strict` attribute that could be passed into `Site`. It was removed a while back when site.render() was removed.

The reasoning for removing the logic was removing a link could create problems with search engines or external links. I wanted to ensure that the

I can see value in it returning if site.render() is to return in some fashion to make room for extensions in the next major update. In the meantime we can add similar logic back into __init__() and logic can check for it in initialize.


My call is to add a `clean_dir:bool = False`


```python
import shutil

class Site():
	...
	def __init__(self, ..., clean_dir: bool=False):
		...
		if clean_dir:
			shutil.rmtree(self.output_dir)
```

**Comment by kjaymiller** [comment]
In #71 I added `clean` as an attribute to `site.render()` which implements the suggestion above.

I pass it into `site render` so that data wasn't deleted until the route_list was updated. This would give people the ability to add logic for more complex updating of files (renaming, etc)
